### ISSUE TITLE
Consolidate Test cases

### ISSUE THREAD

**Issue by danbryce** [ml4ai/funman#2]
Minimum requirements:
- Models: hand coded, bilayer, petrinet to bilayer
- Scenarios: consistency, parameter synth
- Parameter spaces: consolidate 
- Move to scratch: incremental solve, smtlib writing, 
- Keep: cached parameter spaces, 

Default move everything to scratch and pull back what we want.

**Comment by danbryce** [comment]
Resolution:
- minor unit tests in the main funman tests
- scenario examples in funman_demo, with tests and notebooks in funman_demo
- start by putting all tests in scratch and move into right places.

**Comment by danbryce** [comment]
I've moved the tests into scratch, with the exception of one small test in test.  The tests in scratch need triage still.

**Comment by danbryce** [comment]
@dmosaphir Can you decide what tests from `code/funman/scratch/test_param_marginalize.py` and `code/funman/scratch/test_param_marginalization.py` we should keep and make sure that they pass?  Once passing we can move them into `code/funman/test`.  Thanks!

**Comment by dmosaphir** [comment]
Yes sounds good! I’ll work on this today and let you know.  For reference, I have only been using test_param_marginalize.py; I think test_param_marginalization.py can be deleted (it is a deprecated version).

Thanks,
Drisana.
