### ISSUE TITLE
Add time key to parameters

### ISSUE THREAD

**Issue by danbryce** [ml4ai/funman#75]
Check whether the Terrarium syntax for time dependent parameters would be a better representation.  Otherwise, parameters are of the form:

```
{
  "name": "beta",
  "lb": 0.1,
  "ub": 0.2,
  "time": 22
  "label": "any"
}
```

**Comment by danbryce** [comment]
@jgladwig Can you transfer this to siftech/funman?

**Comment by jgladwig** [comment]
Transferred
